# Generated by Django 5.1.2 on 2024-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("hire_date", models.DateField()),
            ],
        ),
    ]
